[tox]
envlist = 
    py{38,39,310,311,312}
    coverage
    lint

[testenv]
description = run tests
commands = python -m tests

[testenv:coverage]
description = code coverage
deps = coverage
commands = coverage report -m

[testenv:lint]
description = lint code
deps = pylint
commands = pylint --rcfile .pylintrc --disable=all --enable=classes password_validator


