[tox]
envlist = 
    py{38,39,310,311,312}
    coverage
    #lint
    #format

[testenv]
description = run tests
commands = python -m tests

[testenv:coverage]
description = code coverage
deps = coverage
commands = coverage report -m

